"""empty message

Revision ID: 0a9e5e1d7e56
Revises: d3fa40fc60a0
Create Date: 2019-12-03 18:09:04.558466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9e5e1d7e56'
down_revision = 'd3fa40fc60a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('firstname', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=256), nullable=True))
    op.drop_constraint('users_name_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_name_key', 'users', ['name'])
    op.drop_column('users', 'password')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
